### PR TITLE
Custom boot flow for PolarFire boards

### PR DESCRIPTION
**Pull request by avpatel**
We have extended Microchip Hart Software Services (HSS) to allow "Custom Boot Flow" on Microchip ICICLE Kit:
`HSS (M-mode) => LOADER (M-mode) => OpenSBI (M-mode) => BOOTLOADER (S-mode)`
where the LOADER can be U-Boot_SPL, Coreboot, or EDK2 (early stages) and BOOTLOADER can be U-Boot_S_mode, EDK2, or Grub2.

There are several advantages of having "Custom Boot Flow" in HSS:
1. It is totally optional and detected from Payload details so the existing boot-flow `HSS (M-mode) => U-Boot (S-mode)` is still available
2. It allows us to use latest OpenSBI with SBI v0.2 and HSM without upgrading OpenSBI linked to HSS
3. It allows use of U-Boot SPL as second stage LOADER but DDR initializing will remain in HSS
4. It allows porting Coreboot and EDK2 to Microchip ICICLE Kit because these projects require booting all HARTs in M-mode

### CODE REVIEW

**Comment by griffini** [comment]
This is pretty cool, thanks for the pull request.  
 
We are in the process of replacing bin2chunks tool with a new payload generator (same file format) tool that uses a (self-documenting) YAML configuration file instead of a cryptic command line.  
 
We're also in the process of replacing the OpenSBI library linked with the HSS with a subtree of upstream, and minimizing the patches to it by using a set of custom extensions instead (to allow the HSS "reboot" a subset of the U54s as needed - for example, if U54_1 and U54_2 were running Linux, and U54_3 and U54_4 were running FreeRTOS or bare metal, we want to be able to reboot each "context" separately).
 
However, I'm wondering if what you are trying to do is already supported by the HSS? If all U54s are specified to boot a common entry point in PRV_M mode, won't it just do what you want? The harts can, in their booted firmware, rewire their SBIs as needed. Did you try this first?

**Comment by avpatel** [comment]
It's not just about having an upgraded OpenSBI linked to HSS. We are working
on OpenSBI domains support which will allow users to partition system into
multiple domains (secure and/or non-secure). We will be using U-Boot SPL
as our LOADER to create domains and load images for domains from the U-Boot
FIT image. The OpenSBI domain support requires all HARTs (both E51 and U54s)
to enter U-Boot SPL in M-mode and eventually enter OpenSBI firmware in M-mode.

To achieve above on Microchip ICICLE board, we encountered following issues:
1. The HSS payload image format only allows specifying entry point, mode
   and images for the U54 HARTs. It does not allow specifying entry point,
   mode and images for the E51 HART. This is a fundamental problem and will
   require new HSS payload image format in long-term.
2. The HSS boot sequence forces E51 HART to always run hss_main() after it
   completes boot sequence. This does not work for OpenSBI domains because
   we want to create separate secure domain for E51 core and run secure
   baremetal application (not linked with OpenSBI) on it.
3. The HSS boot sequence does various initializations (such as setting up
   M-mode CSRs, setting up M-mode PMP regions, etc) for all the U54 HARTs.
   We don't need all these initializations for the U54 HARTs if we are going
   to enter next booting stage in M-mode.
4. The bin2chunks tool forces next mode for all U54 HARTs to be either
   S-mode or U-mode (Refer, validate_privmode_() function in source file
   toots/bin2chunks/bin2chunks.c). I assume this issue is not present in
   the new YAML based HSS payload image generator.

To solve all above issues, this PR implements "custom boot flow" for HSS.

The basic idea is that all HARTs (both E51 and U54s) will jump to the same
entry point in M-mode whenever HSS sees a payload image having same entry
point for all U54 HARTs with entry mode as M-mode.

The EDK2 (UEFI) boot sequence on other hand has various stages and EDK2
expects all HARTs to be started in M-mode. The "custom boot flow" also
unblocks EDK2 (UEFI) porting for Microchip ICICLE board.

Regards,
Anup

**Comment by avpatel** [comment]
I forgot to mention. There is already a standard SBI RESET extension
being discussed on the RISC-V Foundation UnixPlatform mailing list.
(Refer, https://github.com/riscv/riscv-sbi-doc/pull/39)

Please avoid adding HSS specific SBI extension if there is standard SBI
extension already proposed.

Regards,
Anup

**Comment by griffini** [comment]
Okay, thanks for the useful background.  I see where you are coming from now. What you are suggesting is a good use case, and we should examine ways to support it. 

Just some equivalent background on the philosophies behind the HSS. The HSS is designed to support not just for U-Boot and SMP Linux, but also for bare metal payloads -- and in particular, for all sorts of mixed AMP workloads. 

The HSS is essentially part of the tool flow, and a constituent part of ensuring hardware separation. The Microchip Libero SoC tool can be used to partition the system resources between separate hardware contexts, and this is supported by the HSS. This enables the system to be locked down (for hardware separation purposes) before the application firmware is booted.

This partition include memory assignment (L2LIM and DDR), and related protections -- not just the PMPs (which on PolarFire SoC are *lockable* so that they can only be subsequently changed by power cycling) but also the MPUs, which are somewhat equivalent to PMPs for the MSS peripherals.

So the HSS is intended to set up this low-level stuff, and then present a restricted view of the world to OpenSBI, just exposing the remaining PMPs etc. 

> The HSS payload image format only allows specifying entry point, mode and images for the U54 HARTs. It does not allow specifying entry point, mode and images for the E51 HART. _**This is a fundamental problem and will require new HSS payload image format in long-term.**_
> ...
> The HSS boot sequence forces E51 HART to always run hss_main() after it completes boot sequence. This does not work for OpenSBI domains because we want to create separate secure domain for E51 core and run secure bare-metal application (not linked with OpenSBI) on it.

Yes, for what you are trying to achieve, the core problem is that the E51 is deliberately not currently considered or supported for replacement. However, the use case is a very good one, and so extending the payload image format is best way to enable it. 

Using a check on the entry points being the same and booting M-mode is a little hack - perhaps a better mechanism would be to enable this via some field or flag in the boot image format, and also enable/disable this entirely via Kconfig. 

For example, using the same entry point on all 4 U54s in M-mode along with using the HSS services at runtime is also a valid use case that your PR would preclude.

The HSS running on the Icicle board is an all-singing and dancing version that includes USBD-MSC support and a command line, mostly to help in system bring-up, but the intention is that a production HSS would be customised and kept minimal with these extra features turned off - this is the place to enable your custom boot flow.

> The HSS boot sequence does various initializations (such as setting up M-mode CSRs, setting up M-mode PMP regions, etc) for all the U54 HARTs. We don't need all these initializations for the U54 HARTs if we are going to enter next booting stage in M-mode.

One valid use of the tools is for the designer at Libero SoC stage to partition the system - this restricts the resources available to the application programmer through the use of some generated XML which the HSS picks up and converts into auto-generated C code.  As mentioned earlier, this includes peripheral enabling and context assignment (MPUs), a level of memory protection (PMPs), clocks, etc. 

If you want these to be fully open, it is possible to configure it as such in the XML and let the subsequent M-mode firmware (re-)configure all. Additionally, the M-mode CSRs can easily be overwritten by a next-stage M-mode firmware.

> The bin2chunks tool forces next mode for all U54 HARTs to be either S-mode or U-mode (Refer, validate_privmode_() function in source file toots/bin2chunks/bin2chunks.c). I assume this issue is not present in the new YAML based HSS payload image generator.

Correct.

> I forgot to mention. There is already a standard SBI RESET extension being discussed on the RISC-V Foundation Unix Platform mailing list. (Refer, riscv/riscv-sbi-doc#39)
> 
> Please avoid adding HSS specific SBI extension if there is standard SBI extension already proposed.

:+1: 

So the HSS was developed originally without any use of OpenSBI, but when OpenSBI came along, we started refactoring it (and the mpfs-hal) to use it. Our preference is definitely to re-use OpenSBI functionality and interfaces where available :smiley: 

The reboot implementation we are working on now actually uses sbi_reset and sbi_shutdown, but at the moment we have custom implementations of these that we are playing with. We signal back from a U54 to the HSS code running on the E51, and it decides what do to. The HSS needs a way to authenticate that the U54 reboot request is not spoofed, and PMPs are used to enforce this.

This way, it is able to reboot one hardware context while the other continues running.

Note that by replacing the HSS on the E51, the only way left to reboot is to do a full reboot of all Harts, which I guess is okay for your use case.

**Comment by avpatel** [comment]
> Okay, thanks for the useful background. I see where you are coming from now. What you are suggesting is a good use case, and we should examine ways to support it.
> 
> Just some equivalent background on the philosophies behind the HSS. The HSS is designed to support not just for U-Boot and SMP Linux, but also for bare metal payloads -- and in particular, for all sorts of mixed AMP workloads.
> 
> The HSS is essentially part of the tool flow, and a constituent part of ensuring hardware separation. The Microchip Libero SoC tool can be used to partition the system resources between separate hardware contexts, and this is supported by the HSS. This enables the system to be locked down (for hardware separation purposes) before the application firmware is booted.
> 
> This partition include memory assignment (L2LIM and DDR), and related protections -- not just the PMPs (which on PolarFire SoC are _lockable_ so that they can only be subsequently changed by power cycling) but also the MPUs, which are somewhat equivalent to PMPs for the MSS peripherals.
> 
> So the HSS is intended to set up this low-level stuff, and then present a restricted view of the world to OpenSBI, just exposing the remaining PMPs etc.

With OpenSBI domains, we do very similar something for all platforms supported by OpenSBI. Our initial goal is to support, OpenSBI domains on Microchip ICICLE board, SiFive Unleashed, and future SiFive boards.

**Comment by avpatel** [comment]
> Yes, for what you are trying to achieve, the core problem is that the E51 is deliberately not currently considered or supported for replacement. However, the use case is a very good one, and so extending the payload image format is best way to enable it.
> 
> Using a check on the entry points being the same and booting M-mode is a little hack - perhaps a better mechanism would be to enable this via some field or flag in the boot image format, and also enable/disable this entirely via Kconfig.
> 
> For example, using the same entry point on all 4 U54s in M-mode along with using the HSS services at runtime is also a valid use case that your PR would preclude.
> 
> The HSS running on the Icicle board is an all-singing and dancing version that includes USBD-MSC support and a command line, mostly to help in system bring-up, but the intention is that a production HSS would be customised and kept minimal with these extra features turned off - this is the place to enable your custom boot flow.

Okay, I will update the PR to use kconfig option. I will also add HSS defconfigs for ICICLE board.

I think changing the HSS payload image format for "custom boot flow" can be a future addition. For now, a kconfig option is sufficient.

**Comment by griffini** [comment]
Is there a good link to documentation on OpenSBI domains? If we can leverage those to some degree, we could look to refactor...

**Comment by griffini** [comment]
> 
> Okay, I will update the PR to use kconfig option. I will also add HSS defconfigs for ICICLE board.
> 
> I think changing the HSS payload image format for "custom boot flow" can be a future addition. For now, a kconfig option is sufficient.

Thanks, sounds like a good plan for now!

**Comment by avpatel** [comment]
> So the HSS was developed originally without any use of OpenSBI, but when OpenSBI came along, we started refactoring it (and the mpfs-hal) to use it. Our preference is definitely to re-use OpenSBI functionality and interfaces where available smiley
> 
> The reboot implementation we are working on now actually uses sbi_reset and sbi_shutdown, but at the moment we have custom implementations of these that we are playing with. We signal back from a U54 to the HSS code running on the E51, and it decides what do to. The HSS needs a way to authenticate that the U54 reboot request is not spoofed, and PMPs are used to enforce this.
> 
> This way, it is able to reboot one hardware context while the other continues running.
> 
> Note that by replacing the HSS on the E51, the only way left to reboot is to do a full reboot of all Harts, which I guess is okay for your use case.

We have per-domain attribute in OpenSBI domain to know whether a domain is allowed to reset the system or not.

The SBI SRST extension is being proposed for:
1. System-level partitioning solutions (like OpenSBI domains)
2. Guest/VM running on top-of hypervisors
3. Mapping UEFI system reset call implementation in U-Boot and EDK2 to common RISC-V specific reset mechanism

**Comment by avpatel** [comment]
> Is there a good link to documentation on OpenSBI domains? If we can leverage those to some degree, we could look to refactor...

We have v1 patch series of OpenSBI domain under review on OpenSBI mailing list.
(Refer, https://patchwork.ozlabs.org/project/opensbi/list/)

We also presented high-level OpenSBI domain idea yesterday in RISC-V TEE working group.

**Comment by avpatel** [comment]
I have updated the PR to use kconfig option.

Thanks,
Anup

**Comment by avpatel** [comment]
@griffini do you have further comments on this PR ?

Regards,
Anup

**Comment by griffini** [comment]
Thanks for adding the Kconfig option. 

I think it is good for now, and in time will probably refactor some bits out to common code (between your custom flow and the regular boot service).

**Review by griffini — APPROVED** [review]
This changes are good for now, especially seeing as they are wrapped with a Kconfig option. 

In time, we can look to refactor to share common code with the regular boot service, and look to change the boot image format to better support E51 booting.

**Pull request merged**
