### PR TITLE
support for Polarberry added

### PR DESCRIPTION
**Pull request by Mans-sdsp**
# Description

Support for Polarberry is added.

### CODE REVIEW

**Comment by Mans-sdsp** [comment]
Thanks, Conor for your feedback.

Do you need to generate another PR, or you are happy with what you have 
and you can merge it?

Kind regards

On 2023-07-17 05:54, Conor Dooley wrote:

> Hey Mans,
> 
> Was giving this a quick test today & noticed that the def_config in 
> this PR does not link.
> I ran menuconfig & saved the result, leading to the following diff, 
> which did build:
> 
> --- boards/polarberry/def_config    2023-07-17 13:44:49.670380904 +0100
> +++ .config    2023-07-17 13:46:53.478381037 +0100
> @@ -27,6 +27,7 @@
> 
> CONFIG_SERVICE_DDR=y
> CONFIG_SERVICE_GOTO=y
> +# CONFIG_SERVICE_HEALTHMON is not set
> CONFIG_SERVICE_IPI_POLL=y
> CONFIG_SERVICE_MMC=y
> 
> @@ -60,8 +61,33 @@
> # end of MMC
> 
> CONFIG_SERVICE_OPENSBI=y
> +
> +#
> +# SBI Extension Support
> +#
> +CONFIG_SBI_ECALL_TIME=y
> +CONFIG_SBI_ECALL_RFENCE=y
> +CONFIG_SBI_ECALL_IPI=y
> +CONFIG_SBI_ECALL_HSM=y
> +CONFIG_SBI_ECALL_SRST=y
> +CONFIG_SBI_ECALL_PMU=y
> +CONFIG_SBI_ECALL_LEGACY=y
> +CONFIG_SBI_ECALL_VENDOR=y
> +# end of SBI Extension Support
> +
> +CONFIG_FDT_IPI=y
> +CONFIG_FDT_IPI_MSWI=y
> +CONFIG_FDT_IPI_PLICSW=y
> +CONFIG_FDT_IRQCHIP=y
> +CONFIG_FDT_IRQCHIP_PLIC=y
> +CONFIG_FDT_RESET=y
> +CONFIG_FDT_SERIAL=y
> +CONFIG_FDT_SERIAL_UART8250=y
> +CONFIG_FDT_TIMER=y
> +CONFIG_FDT_TIMER_MTIMER=y
> # CONFIG_SERVICE_POWERMODE is not set
> # CONFIG_SERVICE_QSPI is not set
> +CONFIG_SERVICE_REBOOT=y
> # CONFIG_SERVICE_SCRUB is not set
> CONFIG_SERVICE_SGDMA=y
> # CONFIG_SERVICE_SPI is not set
> @@ -122,6 +148,7 @@
> # Cold Reboot
> #
> CONFIG_ALLOW_COLDREBOOT_ALWAYS=y
> +# CONFIG_COLDREBOOT_TRY_AUTO_UPDATE is not set
> # CONFIG_ALLOW_COLDREBOOT_ON_OPENSBI_FAULT is not set
> # end of Cold Reboot
> # end of Miscellaneous
> 
> Things seem to be working as intended, so this looks pretty good to me.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/polarfire-soc/hart-software-services/pull/60#issuecomment-1638086267
[2]

**Comment by ConchuOD** [comment]
> Do you need me to generate another PR, or you are happy with what you have and you can merge it?

I think there may be some comments from the others that they have yet to give, but rather than a new PR, this current one can be updated with the fixups.

**Comment by vfalanis** [comment]
Hey Mans,

Could you please update this PR to include the defconfig changes suggested by Conor? 

We usually ask contributors to include a Signed-off-by tag in commit messages to comply with the Developer Certificate of Origin (DCO) in all of our repositories. Could you please add a Signed-off-by tag to your commit? Instructions on how to do this can be found in the following link: https://volunteer.coscup.org/docs/en/dev/how-to-signoff/

Also, is the Polarberry reference design available in Github or accessible through some other website?

Thanks!

**Comment by ConchuOD** [comment]
@Mans-sdsp Just bumping this PR in case you missed Valentina's comments about the DCO & reference design. Thanks!

**Pull request closed without merging**
